apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-namespace
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: kuard-test-1
        url: https://kubernetes.default.svc 
  template:
    metadata:
      name: application-namespace-{{cluster}}
      namespace: openshift-gitops
    spec:
      destination:
        server: https://kubernetes.default.svc
      project: default
      source:
        path: sample-ns/{{cluster}}
        repoURL: https://github.com/sanjaytripathi97/sample-ns-argo
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true